name: setup-smoketest
description: common setup for pelikan smoketests

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-protoc
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
